baseURL = "https://tpimpinela.github.io/hugo_ssg/"
theme = "hugo-whisper-theme"
languageCode = "en-us"
title = "Tomás Pimpinela | Hugo SSG"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Páginas"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Ver páginas'
  homepage_image = 'banner.jpg'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"

  [params.footer]
    copyright_text = 'Tomás Pimpinela Martínez'
